Repository pymuco/pymuco, pull requests merged in 2023-05, with the labels that each got.

#20 PMC-19 Set up all configuration needed for read the docs
  .readthedocs.yaml
  Makefile
  docs/AudioConverter.rst
  docs/Chord.rst
  docs/CircleOfFifths.rst
  docs/Enharmonic.rst
  docs/EnharmonicMapping.rst
  docs/Interval.rst
  docs/KeySignature.rst
  docs/MIDIUtils.rst
  docs/Makefile
  docs/MusicComputationNotation.rst
  docs/MusicData.rst
  docs/NoteDuration.rst
  docs/NoteFrequencyConverter.rst
  docs/NoteMapping.rst
  docs/Player.rst
  docs/Scale.rst
  docs/ScientificPitchNotation.rst
  docs/Tonality.rst
  docs/conf.py
  docs/index.rst
  docs/modules.rst
  docs/requirements.txt
  docs/setup.rst
  docs/test.rst
  make.bat
  requirements.in
Labels: documentation, good first issue

#21 PMC-18 docs bagde
  README.md
Labels: documentation

#22 PMC-19 readthedocs link
  README.md
Labels: documentation

#24 PMC-20 Add Python Coverage Report to CI
  .github/workflows/python-app.yml
Labels: testing

#25 PMC-21 Update Coverage Data Report
  .github/workflows/python-app.yml
Labels: testing

#28 PMC-22 Refreshing Project Elements
  README.md
  SECURITY.md
  docs/_static/pymucologo.png
  pymuco/AudioConverter.py
  pymuco/Chord.py
  pymuco/CircleOfFifths.py
  pymuco/Enharmonic.py
  pymuco/EnharmonicMapping.py
  pymuco/Interval.py
  pymuco/KeySignature.py
  pymuco/MIDIUtils.py
  pymuco/MusicComputationNotation.py
  pymuco/MusicData.py
  pymuco/NoteDuration.py
  pymuco/NoteFrequencyConverter.py
  pymuco/NoteMapping.py
  pymuco/Player.py
  pymuco/Scale.py
  pymuco/ScientificPitchNotation.py
  pymuco/Tonality.py
Labels: documentation
